import re

def normalize_author(name):
    """
    transform names to a canonical form of last name and first letter of first name,
    with no punctuation, capitalization, or redundant spaces
    eg 'Quine, W. V. O' -> 'quine wvo'
    """
    if not name:
        return name

    # remove punctuation
    name = re.sub('\W+', ' ', name)

    # remove double/trailing spaces
    name = re.sub(' +',' ', name)
    name = name.strip().lower()

    # replace last word (first name) by first letter
    last_word = name.split()[-1]
    name = re.sub('%s$' % last_word, last_word[0], name) if last_word != name and len(last_word) > 2 else name

    # remove spacing between multiple first letters that succeed last name (eg 'w v o' -> 'wvo')
    name = re.sub(' (\w) (\w) (\w)', r' \1\2\3', name)
    name = re.sub(' (\w) (\w)', r' \1\2', name)

    # replace by known name if possible
    return STDNAMES.get(name, name)

def normalize_title(title):
    if not title:
        return title
    title = title.lower()
    title = re.sub('\(.*?\)', '', title) # remove anything in parentheses
    title = re.sub('[^a-zA-Z0-9_-]+', ' ', title) # remove punctuation
    title = title.replace('<it>', '').replace('</it>', '') # remove italics tags
    title = re.sub('^the ', '', title) # remove 'the' prefix
    title = re.sub(' +',' ', title) # remove double spaces
    return title.strip()

def short_title(title):
    title = re.sub('\W+', ' ', title)
    words = title.split()
    title = words[0][:7] + ' ' + ' '.join(w[:3] for w in words[1:5])
    return title

STDNAMES = {
'anscombe': 'anscombe gem',
'anscombe e': 'anscombe gem',
'anscombe em': 'anscombe gem',
'anscomb g': 'anscombe gem',
'anscombe g': 'anscombe gem',
'anscombe ge': 'anscombe gem',
'anscombe gertrude em': 'anscombe gem',
'anscombe gertrude e': 'anscombe gem',
'armstrong d': 'armstrong dm',
'armstrong david m': 'armstrong dm',
'austin john l': 'austin jl',
'belnap': 'belnap nd',
'belnap n': 'belnap nd',
'belnap nuel d': 'belnap nd',
'belnap jr nuel d': 'belnap nd',
'belnap jr nd': 'belnap nd',
'bentham': 'bentham j',
'blum l': 'blum la',
'boghossian p': 'boghossian pa',
'boghossian paul a': 'boghossian pa',
'boolos g': 'boolos gs',
'brandom r': 'brandom rb',
'brandom robert b': 'brandom rb',
'bratman m': 'bratman me',
'bratman michael e': 'bratman me',
'brueckner a': 'brueckner al',
'burgess john p': 'burgess jp',
'burgess j': 'burgess jp',
'burnyeat m': 'burnyeat mf',
'carnap': 'carnap r',
'castancda hn': 'castaneda hn',
'castaneda h': 'castaneda hn',
'castaneda hector n': 'castaneda hn',
'castaneda hr': 'castaneda hn',
'chalmers david j': 'chalmers d',
'chalmers dj': 'chalmers d',
'chalmers jd': 'chalmers d',
'chalmer dj': 'chalmers d',
'chalmer': 'chalmers d',
'chisholm': 'chisholm rm',
'chisholm r': 'chisholm rm',
'chisholm roderick m': 'chisholm rm',
'chomsky': 'chomsky n',
'church': 'church a',
'churchland paul m': 'churchland pm',
'darwall': 'darwall sl',
'darwall s': 'darwall sl',
'darwall stephen l': 'darwall sl',
'de spinoza b': 'spinoza bd',
'definetti b': 'de finetti b',
'finetti b': 'de finetti b',
'finetti bd': 'de finetti b',
'dennett daniel c': 'dennett dc',
'dennett d': 'dennett dc',
'dennett': 'dennett dc',
'descartes': 'descartes r',
'despinoza b': 'spinoza bd',
'dewewy': 'dewey j',
'donnellan': 'donnellan ks',
'donnellan k': 'donnellan ks',
'dretske': 'dretske fi',
'dretske f': 'dretske fi',
'drestke f': 'dretske fi',
'dretske fred i': 'dretske fi',
'dreyfus h': 'dreyfus hl',
'dummett': 'dummett m',
'easwaran kk': 'easwaran k',
'empiricus s': 'sextus e',
'enoch': 'enoch d',
'enochs d': 'enoch d',
'fara delia g': 'fara dg',
'fara d': 'fara dg',
'fara g': 'fara dg',
'feferman': 'feferman s',
'feyerabend p': 'feyerabend pk',
'feyerabend paul k': 'feyerabend pk',
'field h': 'field hh',
'field hartry h': 'field hh',
'fischer john m': 'fischer jm',
'fodor': 'fodor ja',
'fodor j': 'fodor ja',
'fodor jerry a': 'fodor ja',
'frankfurt': 'frankfurt hg',
'frankfurt h': 'frankfurt hg',
'frankfurt harry g': 'frankfurt hg',
'frege gg': 'frege g',
'frege f': 'frege g',
'frege': 'frege g',
'freud': 'freud s',
'geach p': 'geach pt',
'geach peter t': 'geach pt',
'gendler t': 'gendler ts',
'gendler tamar s': 'gendler ts',
'gendler szabo t': 'gendler ts',
'szabo gendler t': 'gendler ts',
'gettier': 'gettier el',
'gettier e': 'gettier el',
'gettier edmund l': 'gettier el',
'gibbard': 'gibbard a',
'godel': 'godel k',
'godfreysmith p': 'godfrey smith p',
'godfreysmith': 'godfrey smith p',
'godfrey sp': 'godfrey smith p',
'godfrey ps': 'godfrey smith p',
'godfrey peter s': 'godfrey smith p',
'goldman a': 'goldman ai',
'goldman alvin i': 'goldman ai',
'goodin r': 'goodin re',
'goodin robert e': 'goodin re',
'grice p': 'grice hp',
'guyer': 'guyer pd',
'guyer p': 'guyer pd',
'hare r': 'hare rm',
'hare richard m': 'hare rm',
'harman g': 'harman gh',
'harman gilbert h': 'harman gh',
'hart h': 'hart hla',
'hegel': 'hegel gwf',
'hegel f': 'hegel gwf',
'hegel g': 'hegel gwf',
'hegel gw': 'hegel gwf',
'hegel georg wilhelm f': 'hegel gwf',
'hegel georg wf': 'hegel gwf',
'heidegger': 'heidegger m',
'hempel': 'hempel cg',
'hempel c': 'hempel cg',
'hempel carl g': 'hempel cg',
'hintikka': 'hintikka j',
'hintikka jaakko k': 'hintikka j',
'hintikka jk': 'hintikka j',
'hintikka k': 'hintikka j',
'hintikka kj': 'hintikka j',
'hintikka kjj': 'hintikka j',
'hobbes': 'hobbes t',
'hobbes th': 'hobbes th',
'hume': 'hume d',
'hurka': 'hurka t',
'irwin t': 'irwin th',
'irwin terence h': 'irwin th',
'jackson f': 'jackson fc',
'jackson frank c': 'jackson fc',
'jeffrey r': 'jeffrey rc',
'jeffrey richard c': 'jeffrey rc',
'joyce j': 'joyce jm',
'joyce james m': 'joyce jm',
'kant': 'kant i',
'kierkegaard': 'kierkegaard s',
'kierkegaard sa': 'kierkegaard s',
'kierkegaard soren a': 'kierkegaard s',
'kim jw': 'kim j',
'king j': 'king jc',
'king jeffrey c': 'king jc',
'korsgaard': 'korsgaard cm',
'korsgraard': 'korsgaard cm',
'korsgaard c': 'korsgaard cm',
'korsgaard ch': 'korsgaard cm',
'korsgaard cn': 'korsgaard cm',
'korsgaard christine m': 'korsgaard cm',
'kripkes': 'kripke sa',
'kripke a': 'kripke sa',
'kripke ks': 'kripke sa',
'kripke': 'kripke sa',
'kripke s': 'kripke sa',
'kripke saul a': 'kripke sa',
'kuhn': 'kuhn ts',
'kuhn t': 'kuhn ts',
'kuhn thomas s': 'kuhn ts',
'kyburg h': 'kyburg he',
'leibnitz': 'leibniz gwv',
'leibnitz g': 'leibniz gwv',
'leibnitz gw': 'leibniz gwv',
'leibniz': 'leibniz gwv',
'leibniz g': 'leibniz gwv',
'leibniz gw': 'leibniz gwv',
'leibniz gottfried wilhelm v': 'leibniz gwv',
'leibniz gottfried w': 'leibniz gwv',
'lewis clarence i': 'lewis ci',
'lewis': 'lewis dk', # confirmed by manually going over the items: almost all 'lewis' references are to david lewis works
'lewis d': 'lewis dk',
'lewis david k': 'lewis dk',
'locke': 'locke j',
'lycan w': 'lycan wg',
'macintyre': 'macintyre ac',
'mcintyre a': 'macintyre ac',
'macintyre a': 'macintyre ac',
'macintyre alasdair c': 'macintyre ac',
'marcus r': 'marcus rb',
'marcus ruth b': 'marcus rb',
'marx': 'marx k',
'mcdowell': 'mcdowell jh',
'mcdowell j': 'mcdowell jh',
'mcdowell john h': 'mcdowell jh',
'mcmahan j': 'mcmahan ja',
'mele al': 'mele ar',
'mele a': 'mele ar',
'mele alfred r': 'mele ar',
'mellor d': 'mellor dh',
'mellor h': 'mellod dh',
'mellor hd': 'mellod dh',
'mill': 'mill js',
'mill john s': 'mill js',
'miller rw': 'miller rwm',
'milikan rg': 'millikan rg',
'millikan r': 'millikan rg',
'millikan ruth': 'millikan rg',
'millikan ruth g': 'millikan rg',
'moore g': 'moore ge',
'moore george e': 'moore ge',
'nietzsche': 'nietzsche fw',
'nietzsche f': 'nietzsche fw',
'nietzsche friedrich w': 'nietzsche fw',
'nozick': 'nozick r',
'robert nozick a': 'nozick r',
'rosenberg j': 'rosenberg jf',
'nussbaum m': 'nussbaum mc',
'nussbaum martha c': 'nussbaum mc',
'parfit': 'parfit da',
'parfit d': 'parfit da',
'parfitt d': 'parfit da',
'parfits d': 'parfit da',
'partee b': 'partee bh',
'partee barbara h': 'partee bh',
'paul laurie a': 'paul la',
'popper': 'popper kr',
'popper k': 'popper kr',
'popper karl r': 'popper kr',
'portmore d': 'portmore dw',
'portmore douglas w': 'portmore dw',
'prior a': 'prior an',
'prior arthur n': 'prior an',
'putnam': 'putnam h',
'quine': 'quine wvo',
'quines': 'quine wvo',
'quine vwo': 'quine wvo',
'quine wv': 'quine wvo',
'quine w': 'quine wvo',
'quine v': 'quine wvo',
'quine vo': 'quine wvo',
'quine wq': 'quine wvo',
'quine wv': 'quine wvo',
'quine wo': 'quine wvo',
'quine willard van o': 'quine wvo',
'quine willard vo': 'quine wvo',
'quine williard v': 'quine wvo',
'quine willard v': 'quine wvo',
'quine wvan o': 'quine wvo',
'vanoquine w': 'quine wvo',
'vanquine w': 'quine wvo',
'van quine w': 'quine wvo',
'van quine wo': 'quine wvo',
'vanquine wo': 'quine wvo',
'vonquine wo': 'quine wvo',
'vanormanquine w': 'quine wvo',
'van orman quine w': 'quine wvo',
'quine willardv o': 'quine wvo',
'quine williard van o': 'quine wvo',
'quine wo': 'quine wvo',
'van quine willard o': 'quine wvo',
'ramsey f': 'ramsey fp',
'ramsey pf': 'ramsey fp',
'ramsey frank p': 'ramsey fp',
'rawls': 'rawls jb',
'rawls j': 'rawls jb',
'raz': 'raz j',
'reichenbach': 'reichenbach h',
'ross william d': 'ross wd',
'rousseau': 'rousseau jj',
'rousseau j': 'rousseau jj',
'rousseau jean j': 'rousseau jj',
'roussean jj': 'rousseau jj',
'russell': 'russell b',
'ryle': 'ryle g',
'sainsbury r': 'sainsbury rm',
'salmon nathan u': 'salmon nu',
'salmon n': 'salmon nu',
'sartre': 'sartre jp',
'sartre j': 'sartre jp',
'sartre jean p': 'sartre jp',
'scanlon': 'scanlon tm',
'scanlon t': 'scanlon tm',
'scanlon thomas m': 'scanlon tm',
'scanlon timothy m': 'scanlon tm',
'scanlon tim m': 'scanlon tm',
'schopenhauer': 'schopenhauer a',
'searle': 'searle jr',
'searle j': 'searle jr',
'searle john r': 'searle jr',
'sen a': 'sen ak',
'sellars w': 'sellars ws',
'sellars wf': 'sellars ws',
'sellars wilfred s': 'sellars ws',
'sellars wilfrid s': 'sellars ws',
'smart j': 'smart jjc',
'smart jc': 'smart jjc',
'smart jj': 'smart jjc',
'soames': 'soames s',
'sorensen r': 'sorensen ra',
'sorensen roy a': 'sorensen ra',
'spinoza': 'spinoza bd',
'spinoza b': 'spinoza bd',
'spinoza benedict de': 'spinoza bd',
'spinoza benedictus de': 'spinoza bd',
'stalnake rc': 'stalnaker rc',
'stalnaker': 'stalnaker rc',
'stalnaker r': 'stalnaker rc',
'stalnaker robert c': 'stalnaker rc',
'strawson p': 'strawson pf',
'sturgeon n': 'sturgeon nl',
'sturgeon nicholas l': 'sturgeon nl',
'thomson j': 'thomson jj',
'thomson judith j': 'thomson jj',
'turing': 'turing am',
'turing a': 'turing am',
'turing alan m': 'turing am',
'van benthem j': 'van benthem jf',
'van fraassen b': 'van fraassen bc',
'vanfraassen b': 'van fraassen bc',
'vansfraassen b': 'van fraassen bc',
'vanfraassen bc': 'van fraassen bc',
'vanfraasen bc': 'van fraassen bc',
'van fraassen bas c': 'van fraassen bc',
'fraassen bv': 'van fraassen bc',
'basvanfraassen': 'van fraassen bc',
'fraasen bv': 'van fraassen bc',
'fraassen bv': 'van fraassen bc',
'fraassen bas c': 'van fraassen bc',
'fraassen bc': 'van fraassen bc',
'fraassen b': 'van fraassen bc',
'fraassen v': 'van fraassen bc',
'van fraasen b': 'van fraassen bc',
'van fraassen bastian c': 'van fraassen bc',
'van fraassen c': 'van fraassen bc',
'van fraassen sb': 'van fraassen bc',
'vanfraas bc': 'van fraassen bc',
'vanfraasen b': 'van fraassen bc',
'vanfraasenbas': 'van fraassen bc',
'vanfraassen': 'van fraassen bc',
'vanfraassen c': 'van fraassen bc',
'vanfraassens b': 'van fraassen bc',
'van fraasen b': 'van fraassen bc',
'van fraassen bastian c': 'van fraassen bc',
'van fraassen c': 'van fraassen bc',
'van fraassen sb': 'van fraassen bc',
'vanfraas bc': 'van fraassen bc',
'vanfraasen b': 'van fraassen bc',
'vanfraasenbas': 'van fraassen bc',
'vanfraassen': 'van fraassen bc',
'vanfraassen c': 'van fraassen bc',
'vanfraassens b': 'van fraassen bc',
'vansfraassen bc': 'van fraassen bc',
'vanvfraassen b': 'van fraassen bc',
'vaninwagen': 'van inwagen p',
'vaninwagen p': 'van inwagen p',
'inwagen van p': 'van inwagen p',
'vansinwagen p': 'van inwagen p',
'inwagen p': 'van inwagen p',
'inwagen peter v': 'van inwagen p',
'inwagen pv': 'van inwagen p',
'inwagen v': 'van inwagen p',
'vaninwagenp': 'van inwagen p',
'vonfintel k': 'von fintel k',
'fintel kv': 'von fintel k',
'vonsfintel': 'von fintel k',
'vonsfintel k': 'von fintel k',
'velleman j': 'velleman jd',
'velleman d': 'velleman jd',
'velleman dj': 'velleman jd',
'velleman james d': 'velleman jd',
'velleman': 'velleman jd',
'david velleman j': 'velleman jd',
'williams b': 'williams ba',
'williams bernard a': 'williams ba',
'williams bernard ao': 'williams ba',
'williams bernard arthur o': 'williams ba',
'wiliamson t': 'williamson t',
'wiliamson': 'williamson t',
'williamson': 'williamson t',
'wilson jessica m': 'willson jm',
'wilson j': 'wilson jm',
'wittgenstein': 'wittgenstein l',
'wittgenstein lj': 'wittgenstein l',
'wittgenstein ljj': 'wittgenstein l',
'wittgenstein ludwig jj': 'wittgenstein l',
'wittgenstein ludwig bb': 'wittgenstein l',
'wittgenstien l': 'wittgenstein l',
'wittgenstain l': 'wittgenstein l',
'wittgenstein z': 'wittgenstein l',
'wittgenstain w': 'wittgenstein l',
'wittgensten': 'wittgenstein l',
'wittgensteins': 'wittgenstein l',
'wittgentsein l': 'wittgenstein l',
'yablo': 'yablo s',
'zagzebski l': 'zagzebski lt',
'zagzebskis l': 'zagzebski lt',
'zagzebski linda t': 'zagzebski lt',
'zalta e': 'zalta en',
'zalta edward n': 'zalta en',
 }
